homebrew_packages:
  - { name: python }
  - { name: coreutils }
  - { name: ctags }
  - { name: git }
  - { name: wget }
  - { name: curl }
  - { name: tree }
  - { name: nkf }
  - { name: jq }
  - { name: peco }
  - { name: php-code-sniffer }
  - { name: hub }
  - { name: node }
  - { name: tig }
  - { name: rbenv }
  - { name: ruby-build }
  - { name: tofrodos }
  - { name: tmux }
  - { name: reattach-to-user-namespace }
  - { name: gibo }
  - { name: the_silver_searcher}
  - { name: source-highlight }
  - { name: vim, options: 'with-lua' }
  - { name: zsh }
  - { name: awscli }
  - { name: go }
#  - { name: terraform }
  - { name: tfenv }
  - { name: packer }
  - { name: mysql }
  - { name: ctop }
  - { name: awslogs }
  - { name: yarn }
  - { name: knqyf263/utern/utern }
  - { name: hugo }
  - { name: amazon-ecs-cli }
  - { name: mkcert }
  - { name: nss }
homebrew_cask_packages:
  - { name: iterm2 }
  - { name: google-chrome }
  - { name: slack }
  - { name: vagrant }
  - { name: virtualbox }
  - { name: the-unarchiver }
  - { name: alfred }
  - { name: onyx }
  - { name: shiftit }
  - { name: pomotodo }
  - { name: docker }
  - { name: firefox }
  - { name: appcleaner }
  - { name: licecap }
  - { name: cyberduck }
  - { name: spotify }
  - { name: keka }
  - { name: cmd-eikana }
  - { name: kindle }
  - { name: dash }
  - { name: spotmenu }
  - { name: visual-studio-code }
  - { name: keyboardcleantool }
  - { name: postman }
  - { name: aws-vault }
  - { name: bitwarden }
  - { name: google-cloud-sdk }
  - { name: toggl }
  - { name: hyper }
  - { name: java }
  - { name: vagrant }
  - { name: drawio }
gem_packages:
  - { name: terraforming }
  - { name: iStats }
  - { name: bundler }
  - { name: sass }
npm_packages:
  - { name: gtop }
  - { name: serverless }
pip_packages:
  - { name: cfn-lint }
