homebrew_taps:
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - caskroom/cask
homebrew_packages:
  - { name: python }
  - { name: ansible }
  - { name: coreutils }
  - { name: ctags }
  - { name: git }
  - { name: wget }
  - { name: curl }
  - { name: tree }
  - { name: nkf }
  - { name: jq }
  - { name: peco }
  - { name: php-code-sniffer }
  - { name: hub }
  - { name: node }
  - { name: tig }
  - { name: rbenv }
  - { name: ruby-build }
  - { name: tofrodos }
  - { name: tmux }
  - { name: reattach-to-user-namespace }
  - { name: gibo }
  - { name: the_silver_searcher}
  - { name: source-highlight }
  - { name: vim, options: 'with-lua' }
  - { name: zsh }
  - { name: graphviz }
  - { name: awscli }
  - { name: redpen }
  - { name: elixir }
  - { name: go }
  - { name: terraform }
  - { name: packer }
homebrew_cask_packages:
  - { name: iterm2 }
  - { name: google-chrome }
  - { name: adobe-reader }
  - { name: slack }
  - { name: gitx }
  - { name: atom }
  - { name: vagrant }
  - { name: virtualbox }
  - { name: the-unarchiver }
  - { name: alfred }
  - { name: onyx }
  - { name: shiftit }
  - { name: phpstorm }
  - { name: pomotodo }
  - { name: visual-studio-code }
  - { name: apache-directory-studio }
  - { name: java }
  - { name: docker }
  - { name: firefox }
  - { name: google-play-music-desktop-player }
  - { name: appcleaner }
  - { name: soundnode }
  - { name: licecap }
  - { name: macdown }
  - { name: cyberduck }
  - { name: spotify }
  - { name: keka }
  - { name: franz }
  - { name: vmware-fusion }
  - { name: cmd-eikana }
gem_packages:
  - { name: terraforming }
npm_packages:
  - { name: serverless }
#pip_packages:
