---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications --caskroom=/opt/homebrew-cask/Caskroom"

  roles:
    - { role: brew, tags: brew }
    - { role: fonts, tags: fonts }
    - { role: zsh, tags: zsh }
    - { role: dotfiles, tags: dotfiles }
    - { role: vim, tags: vim }
