---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"

  roles:
    - { role: packages, tags: packages }
    - { role: fonts, tags: fonts }
    - { role: zsh, tags: zsh }
    - { role: dotfiles, tags: dotfiles }
    - { role: vim, tags: vim }
    - { role: tools, tags: tools }
